### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by tuxayo** [jpmac26/DRV3-Tools#3]
I see a .pro file does this mean that importing in Qt Creator should be straightforward or are there other thing to pay attention about?

**Comment by CaptainSwag101** [comment]
As far as I'm aware, building via Qt Creator should be fairly simple, but in fairness I have not tested or updated this project in quite some time. Over the past few years I have also encountered a wide variety of issues building C++ software on my computer for very cryptic reasons, so your mileage may vary.

If you're looking for a potentially easier time compiling, I've rewritten most of these tools in C#, a language I'm more familiar in. That project is also available from my GitHub, called "DRV3-Sharp", and it _should_ have implementations of all the tools used here, and in fact are more accurate or have more features than these tools in some cases, due to longstanding bugs in my old implementations that I fixed when originally porting them to C# or improvements I've made later on.

I originally wrote these tools in C++ as an attempt to improve my knowledge of the language, and also due to my original assumption that SPC compression would be far too slow if implemented in something like C#, which has since been proven untrue. DRV3-Sharp's tools are based on .NET Core 3.1 and should be very easy to build on any system (including macOS and Linux with the exception of the GUI apps), though I personally use VS2019 Community on Windows 10.

If you do wish to continue using these apps and encounter problems (which you might not), I sadly cannot provide build support due to lack of experience and the general cryptic and inconsistent nature of compiling C++ code. I highly recommend using DRV3-Sharp if at all possible.
